blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

infobeans_polling/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from infobeans_polling_app import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.indexView.as_view(), name='indexView'),
    path('home/', views.home, name='home'),
    path('infobeans_polling_app/', include('infobeans_polling_app.urls')),
    path('admin/', admin.site.urls),
    path('special/', views.special, name='special'),
    # path('userauth_app/', include('userauth_app.urls')),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('result/<poll_id>/', views.result, name='result'),
    path('vote/<poll_id>/', views.vote, name='vote'),
    path('profile/', views.profile, name='profile'),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/', include("groups.urls", namespace="groups")),
    path('blog/', include(('blog.urls', 'blog'), namespace="blog")),
]

# Only add this when we are in debug mode.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infobeans_polling_app/urls.py
from django.urls import path
from . import views
from infobeans_polling_app import views

# SET THE NAMESPACE!
app_name = 'infobeans_polling_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    # path('user_register/',views.user_register,name='user_register'),
    path('user_register/', views.user_register, name='user_register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('create/', views.create, name='create'),

]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    # path('accounts/', include("accounts.urls", namespace="accounts")),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
]

templates/footer.html
    {% block footer %}
<div class="copy">
            <div class="container">
                <a href="https://www.infobeans.com/" target="_blank">2023 &copy; All Rights Reserved | Designed and Developed by infobeans.com</a>
                <span>
                    <a href=""><i class="fab fa-github"></i></a>
                    <a href=""><i class="fab fa-google-plus-g"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                </span>
            </div>
        </div>
 {% endblock %}
    </body>
</html>

templates/header.html
<!doctype html>
    <html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>InfoBeans Polling</title>
        <link rel="shortcut icon" href="assets/images/fav.png" type="image/x-icon">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="shortcut icon" href="{% static 'images/fav.jpg' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
    </head>
     <body>
     {% block header %}
        <div class="header container-fluid bg-white">
            <div id="menu-jk" class="nav-col text-white shadow-md mb-3">
                <div class="container">
                    <div class="row" style="width:125%">
                        <div class="col-lg-6 pt-2 pb-2 align-items-center">
                            <a href="{% url 'indexView' %}" class="fw-bold fs-8 text-primary"> <img class="max-230 mt-2" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUSaKjA7Cg60bHX9Gd7E7SNFoNpIsiBlaLVZXF0mlzyyunKbnS9qh4-Zf-8K7SoxOEJQ&usqp=CAU" alt="logo" width="190px"></a>
                            <a  data-bs-toggle="collapse" data-bs-target="#menu" class="float-end text-dark d-lg-none pt-1 ps-3"><i class="bi pt-1 fs-1 cp bi-list"></i></a>
                        </div>
                        <div id="menu" class="col-lg-6 d-none d-lg-block">
                            <ul class="float-end mul d-inline-block">
                                 {% if user.is_authenticated %}
                                 <li class="float-md-start px-4 pe-1 pt-4">
                                   <a href="{% url 'home' %}" class="fw-bold fs-8 text-primary"> View Survey List</a>
                                </li>
                                <li class="float-md-start px-4 pe-1 pt-4">
                                   <a href="{% url 'infobeans_polling_app:create' %}" class="fw-bold fs-8 text-primary"> Create Polling survey</a>
                                </li>

                                 <li class="float-md-start px-4 pe-1 pt-4">
                                          <div class="dropdown pmd-dropdown pmd-user-info ml-auto">
                                                <a class="fw-bold fs-8 text-primary" href="{% url 'blog:post_list' %}" class="btn btn-simple">Blogs</a>
                                              <ul class="dropdown-menu dropdown-menu-right" role="menu">
<!--                                                   <a class="dropdown-item" href="% url 'user_poll_list' %">My Post Questions</a>-->
                                                  <a class="dropdown-item" href="{% url 'blog:post_new' %}" class="btn btn-simple">Create Blog</a>
                                                    <a class="dropdown-item" href="{% url 'blog:post_draft_list' %}" class="btn btn-simple">Drafts</a>

                                                </ul>
                                          </div>

<!--                                   <a href="{% url 'profile' %}"  class="fw-bold fs-8 text-primary"> View profile</a>-->
                                </li>


                                <li class="float-md-start px-4 pe-1 pt-4">
                                          <div class="dropdown pmd-dropdown pmd-user-info ml-auto">
                                                <a class="fw-bold fs-8 text-primary" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
                                              <ul class="dropdown-menu dropdown-menu-right" role="menu">
<!--                                                   <a class="dropdown-item" href="% url 'user_poll_list' %">My Post Questions</a>-->
                                                  <a class="dropdown-item" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
                                                    <a class="dropdown-item" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>

                                                </ul>
                                          </div>

<!--                                   <a href="{% url 'profile' %}"  class="fw-bold fs-8 text-primary"> View profile</a>-->
                                </li>

                                 <li class="float-md-start px-4 pe-1 pt-4">
                                          <div class="dropdown pmd-dropdown pmd-user-info ml-auto">
                                                 <a href="javascript:void(0);" class="btn-user media align-items-center" data-toggle="dropdown" data-sidebar="true" aria-expanded="false">
                                                     <img class="rounded-circle account-img " src="{{ user.profile.image.url }}" width="35" height="35"/>


                                                 </a>
                                              <ul class="dropdown-menu dropdown-menu-right" role="menu">
<!--                                                   <a class="dropdown-item" href="% url 'user_poll_list' %">My Post Questions</a>-->
                                                    <a class="dropdown-item" href="{% url 'profile' %}">Edit Profile</a>
                                                    <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
                                                </ul>
                                          </div>

<!--                                   <a href="{% url 'profile' %}"  class="fw-bold fs-8 text-primary"> View profile</a>-->
                                </li>



                                 {% endif %}


                                {% if not user.is_authenticated %}
                                <li class="float-md-start px-4 pe-1 pt-4">
                                   <a href="{% url 'infobeans_polling_app:user_login' %}" class="fw-bold fs-8 text-primary"> Login</a>
                                </li>

                                <li class="float-md-start px-4 pe-1 pt-4">
                                   <a href="{% url 'infobeans_polling_app:user_register' %}"  class="fw-bold fs-8 text-primary">Registration</a>
                                </li>
                                {% endif %}



<!--                                 <li class="float-md-start px-4 pe-1 pt-4">-->
<!--                                   <a href="{% url 'user_logout' %}"  class="fw-bold fs-8 text-primary"> Logout</a>-->
<!--                                </li>-->


                            </ul>


                        </div>
                    </div>
                </div>
            </div>
        </div>
 {% endblock %}

templates/home.html
{% include "header.html" %}
{% load static %}

{% block header %}

  <section class="h-100 gradient-form">
  <div class="container py-5">
<div class="accordion">

        <h1 class="accordion-title">Available Polls</h1>
 {% for poll in polls %}
        <div class="content-container">
            <div class="question">{{ poll.question }}</div>
            <div class="answer"> <a href="{% url 'vote' poll.id %}" class="btn btn-info">Vote</a> &nbsp;
                        <a href="{% url 'result' poll.id %}" class="btn btn-info">View Results</a> &nbsp;

            </div>
        </div>
{% endfor %}
      </div>
  </div>
</section>
    {% endblock %}


{% block content %}
    {% include "footer.html" %}
{% endblock %}

<script>
    const accordion = document.getElementsByClassName("content-container");

for (let i = 0; i < accordion.length; i++) {
  accordion[i].addEventListener("click", function () {
    this.classList.toggle("active");
    console.log(this);
  });
}

</script>

templates/index.html
{% include "header.html" %}

{% block header %}

<!-- Carousel wrapper -->
<div
  id="carouselBasicExample"
  class="carousel slide carousel-fade"
  data-mdb-ride="carousel"
 style="margin-top: -15px;">
  <!-- Indicators -->
  <div class="carousel-indicators">
    <button
      type="button"
      data-mdb-target="#carouselBasicExample"
      data-mdb-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-mdb-target="#carouselBasicExample"
      data-mdb-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-mdb-target="#carouselBasicExample"
      data-mdb-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>

  <!-- Inner -->
  <div class="carousel-inner">
    <!-- Single item -->
    <div class="carousel-item active">
      <img
        src="https://img.freepik.com/free-photo/young-business-woman-checking-satisfaction-checklist-box-copy-space_1258-88647.jpg?w=1060&t=st=1688377266~exp=1688377866~hmac=ed9b646da942afa68739e3be533294c84fdfa2d1415f02d0051589b3c95dc0b9"
        class="d-block w-100"
        alt="Sunset Over the City"
      />
     
    </div>

   
  </div>

</div>
<!-- Carousel wrapper -->

{% endblock %}


{% block content %}
    {% include "footer.html" %}
{% endblock %}

templates/poll_list.html
{% include "header.html" %}

{% block header %}
{% load crispy_forms_tags  %}
<section class="h-100 gradient-form">
  <div class="container py-5">

{% for poll in polls %}
    <div>
        <h3>{{ poll.title }}</h3>
        <p>Posted by: {{ poll.user.username }}</p>
        <p>Created at: {{ poll.created_at }}</p>
    </div>
{% empty %}
    <p>No posts found.</p>
{% endfor %}

      </div>
</section>
    {% endblock %}


{% block content %}
    {% include "footer.html" %}
{% endblock %}

templates/profile.html
{% include "header.html" %}
{% block header %}
{% load crispy_forms_tags  %}
<section class="h-100 gradient-form">
  <div class="container py-5">

<div class="content-section custom_css">
  <div class="media">
    <img
      class="rounded-circle account-img"
      src="{{ user.profile.image.url }}" width="100" height="100"
    />
    <div class="media-body">
      <h2 class="account-heading" >{{ user.username }}</h2>
      <p class="text-secondary" style="color:#fff!important">{{ user.email }}</p>
    </div>
  </div>
  <!-- FORM HERE -->
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4" style="color:#fff!important">Profile Info</legend>
       {{ u_form|crispy }}
      <!-- User form -->
      {{ p_form|crispy }}
      <!-- Profile form -->
    </fieldset>
    <div class="form-group">
      <br/>
      <button class="btn btn-info" type="submit">Update</button>
    </div>
  </form>
</div>
  <!-- FORM HERE -->
</div>
  </div>
</section>
        {% endblock %}


{% block content %}
    {% include "footer.html" %}
{% endblock %}

templates/result.html
{% include "header.html" %}

{% block header %}
<section class="h-100 gradient-form">
  <div class="container py-5">
        <div class="container py-5 big-padding custom_css">
            <div class="row section-title">
                <h1 class=" text-center"> {{ poll.question }}</h1>
                <h2>Total Vote : {{ poll.total }}</h2>
                 <img
    class="rounded-circle article-img"
    src="{{ post.author.profile.image.url }}"
  />
            </div>
            <div class="row mb-5">
                <div class="col-md-6 mb-4">
                   <div class="row shado-md p-2 m-0 rounded shadow-md bg-white">
                       <div class="col-md-3">
                           <div id="div1" class="fa rounded-pill max-130 p-2" style="font-size:48px;color:red;margin:14px"></div>

                       </div>
                       <div class="col-md-9 align-self-center">
                           <h4 class="mt-3 fs-5 mb-1 fw-bold">{{ poll.option_one }}</h4>
                           <p class="fs-8 mb-2 fw-bold">Votes : {{ poll.option_one_count }}</p>
                           <div class="progress">
                              <div class="progress-bar bg-danger" role="progressbar" aria-label="Example with label"   aria-valuemin="0" aria-valuemax="100">25%</div>
                          </div>
                       </div>
                   </div>
                </div>

                <div class="col-md-6 mb-4">
                   <div class="row shado-md p-2 m-0 rounded shadow-md bg-white">
                       <div class="col-md-3">
                            <div id="div2" class="fa rounded-pill max-130 p-2" style="font-size:48px;color:red;margin:14px"></div>
                       </div>
                       <div class="col-md-9 align-self-center">
                           <h4 class="mt-3 fs-5 mb-1 fw-bold">{{ poll.option_two }}</h4>
                           <p class="fs-8 mb-2 fw-bold"> Votes :  {{ poll.option_two_count }}</p>
                           <div class="progress">
                              <div class="progress-bar bg-warning" role="progressbar" aria-label="Example with label" style="width: 55%;" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100">25%</div>
                          </div>
                       </div>
                   </div>
                </div>

                <div class="col-md-6 mb-4">
                   <div class="row shado-md p-2 m-0 rounded shadow-md bg-white">
                       <div class="col-md-3">
                        <div id="div3" class="fa rounded-pill max-130 p-2" style="font-size:48px;color:red;margin:14px"></div>
                       </div>
                       <div class="col-md-9 align-self-center">
                           <h4 class="mt-3 fs-5 mb-1 fw-bold">{{ poll.option_three }}</h4>
                           <p class="fs-8 mb-2 fw-bold">Votes : {{ poll.option_three_count }}</p>
                           <div class="progress">
                              <div class="progress-bar bg-primary" role="progressbar" aria-label="Example with label" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
                          </div>
                       </div>
                   </div>
                </div>

            </div>
        </div>
  </div>
</section>
        {% endblock %}


{% block content %}
    {% include "footer.html" %}
{% endblock %}

<script>
function ratestar() {
  var a;
  var b;
  var c;
  a = document.getElementById("div1");
  b = document.getElementById("div2");
  c = document.getElementById("div3");

  a.innerHTML = "&#xf006;";
  setTimeout(function () {
      a.innerHTML = "&#xf123;";
    }, 1000);
  setTimeout(function () {
      a.innerHTML = "&#xf005;";
    }, 2000);


    b.innerHTML = "&#xf006;";
  setTimeout(function () {
      b.innerHTML = "&#xf123;";
    }, 1000);
  setTimeout(function () {
      b.innerHTML = "&#xf005;";
    }, 2000);

      c.innerHTML = "&#xf006;";
  setTimeout(function () {
      c.innerHTML = "&#xf123;";
    }, 1000);
  setTimeout(function () {
      c.innerHTML = "&#xf005;";
    }, 2000);
}
ratestar();
setInterval(ratestar, 3000);
</script>

templates/vote.html
{% include "header.html" %}
{% load static %}

{% block header %}
<section class="h-100 gradient-form">
  <div class="container py-5">
<div class="row custom_css">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Cast Your Vote</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>{{ poll.question }}</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <hr />

                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="poll" value="option1" required>
                                        {{ poll.option_one }}
                                    </label> &nbsp;
                                    <label>
                                        <input type="radio" name="poll" value="option2">
                                        {{ poll.option_two }}
                                    </label> &nbsp;
                                    <label>
                                        <input type="radio" name="poll" value="option3">
                                        {{ poll.option_three }}
                                    </label> &nbsp;
                                </div>
                            </div>

                            <hr />

                            <button type="submit" class="btn btn-info">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
  </div>
</section>
    {% endblock %}


{% block content %}
    {% include "footer.html" %}
{% endblock %}